# Configuration parameters for running repeated mission loops.

rosbag_topics:
  - '/rosout_agg/(.*)'
  - '/rosout'
  - '/twist_marker_server/(.*)'
  - '/localization_helper/(.*)'
  - '/localization_core/(.*)'
  - '/piksi_position/(.*)'
  - '/piksi_heading/(.*)'

mission_files:
  - '/home/administrator/outdoornav_ws/src/cpr_outdoornav/src/cpr_onav_api_examples/config/missions/loop_ccw.yaml'
  - '/home/administrator/outdoornav_ws/src/cpr_outdoornav/src/cpr_onav_api_examples/config/missions/loop_cw.yaml'
